### ISSUE TITLE
ssltest Windows

### ISSUE THREAD

**Issue by gitqlt** [ChristopherSchultz/ssltest#1]
should run on Windows? Compiling and creating jar is OK. Then it crashes
`Exception in thread "main" java.security.NoSuchAlgorithmException: NativePRNG SecureRandom not available`
        at sun.security.jca.GetInstance.getInstance(Unknown Source)
        at java.security.SecureRandom.getInstance(Unknown Source)
        at net.christopherschultz.ssltest.SSLTest.main(SSLTest.java:350)
```

**Comment by ChristopherSchultz** [comment]
Odd that Java on Windows doesn't provide a "native" PRNG. Oh, wait... it does, but under a different name. Try changing `NativePRNG` on line 350 to `Windows-PRNG`.

**Comment by ChristopherSchultz** [comment]
@gitqlt Did changing the PRNG work for you? I'd prefer not to build-in platform-detection to pick a `SecureRandom` implementation, but it looks like I might have to do that, or something like it.

**Comment by ChristopherSchultz** [comment]
Commit f125e1322787d7b7a43e9652d97ad8fc38096315 fixes this issue.
