### ISSUE TITLE
Proxy server?

### ISSUE THREAD

**Issue by erictinsley** [ChristopherSchultz/ssltest#3]
Is there any way to make this work with a proxy server that requires authentication?

**Comment by erictinsley** [comment]
I found this while searching for a way to do it.  I know very little about java so please excuse my ignorance.

> When a proxy server requires authentication, it responds to connection requests with a credential request.  In Java, this is handled by setting a default authenticator.  There are numerous authentication types that are supported by Java.  In this example, we will be using a simple username and password authenticator.
> 
> Add the following code to your client and initialize the proxy authenticator before creating any connections:

```
private void initializeProxyAuthenticator() {
    final String proxyUser = System.getProperty("http.proxyUser");
    final String proxyPassword = System.getProperty("http.proxyPassword");

    if (proxyUser != null && proxyPassword != null) {
        Authenticator.setDefault(
          new Authenticator() {
            public PasswordAuthentication getPasswordAuthentication() {
              return new PasswordAuthentication(
                proxyUser, proxyPassword.toCharArray()
              );
            }
          }
        );
    }
}

```

> Finally, set the following Java system properties:

```
-Dhttp.proxyUser=<proxy user>
-Dhttp.proxyPassword=<proxy password>
```
[https://blogs.oracle.com/wssfc/handling-proxy-server-authentication-requests-in-java](url)

[https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html](url)

**Comment by ChristopherSchultz** [comment]
Hmm. I was about to write "just set your system properties for your proxy and you should be all set" but in this case, `SSLTest` isn't using `Http(s)URLConnection` which would use these proxy system properties. `SSLTest` uses direct sockets, so a proxy isn't directly-supported.

This will take some thinking. I'm not excited about the prospect of implementing the proxy protocol in `SSLTest`, even though it is a fairly simple protocol.

**Comment by ChristopherSchultz** [comment]
Could you please check the section on "SOCKS" here and let me know if setting those system properties works for you? https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

**Comment by ChristopherSchultz** [comment]
Were you ever able to check out the use of SOCKS proxy from Java, Eric?

**Comment by ChristopherSchultz** [comment]
It's been a year with no response. Closing this issue.
